"""Canonical tag catalogs, featured subsets and normalization aliases.

Each catalog is sorted alphabetically. Featured subsets are curated for UI
quick-pick widgets and should remain small (≤30 entries). Aliases map common
alternate spellings and abbreviations to their canonical form.
"""

from __future__ import annotations

from app.games.tags._types import TagKind

# ---------------------------------------------------------------------------
# Genre
# ---------------------------------------------------------------------------

GENRE_TAG_CATALOG: list[str] = [
    "4x",
    "action",
    "action roguelike",
    "action rpg",
    "adventure",
    "arcade",
    "asymmetric multiplayer",
    "auto battler",
    "base building",
    "battle royale",
    "beat em up",
    "bullet heaven",
    "card battler",
    "card game",
    "city builder",
    "colony sim",
    "cooperative",
    "cozy",
    "crafting",
    "crpg",
    "cyberpunk",
    "daily challenge",
    "dating sim",
    "deckbuilder",
    "detective",
    "dungeon crawler",
    "escape room",
    "extraction shooter",
    "factory automation",
    "fantasy",
    "farming sim",
    "fighting",
    "first-person shooter",
    "fishing",
    "flight sim",
    "grand strategy",
    "hack and slash",
    "hero shooter",
    "hidden object",
    "horror",
    "idle",
    "immersive sim",
    "incremental",
    "interactive fiction",
    "isometric",
    "jrpg",
    "life sim",
    "looter shooter",
    "management",
    "match-3",
    "metroidvania",
    "moba",
    "monster taming",
    "musou",
    "mystery",
    "narrative adventure",
    "nonogram",
    "open world",
    "party game",
    "physics puzzle",
    "platformer",
    "point and click",
    "precision platformer",
    "psychological horror",
    "puzzle",
    "puzzle platformer",
    "racing",
    "real-time strategy",
    "rhythm",
    "roguelike",
    "roguelite",
    "rpg",
    "run and gun",
    "sandbox",
    "sci-fi",
    "shmup",
    "simulation",
    "social deduction",
    "soulslike",
    "space",
    "space sim",
    "sports",
    "stealth",
    "strategy",
    "survival",
    "survival horror",
    "tabletop sim",
    "tactical rpg",
    "tactics",
    "text adventure",
    "third-person shooter",
    "top-down shooter",
    "tower defense",
    "trading card game",
    "trivia",
    "turn-based combat",
    "turn-based strategy",
    "turn-based tactics",
    "twin-stick shooter",
    "vehicle combat",
    "visual novel",
    "walking simulator",
    "wargame",
    "wholesome",
    "word game",
]

FEATURED_GENRE_TAGS: list[str] = [
    "action rpg",
    "arcade",
    "battle royale",
    "beat em up",
    "city builder",
    "daily challenge",
    "deckbuilder",
    "factory automation",
    "fighting",
    "first-person shooter",
    "jrpg",
    "metroidvania",
    "moba",
    "narrative adventure",
    "platformer",
    "puzzle",
    "racing",
    "real-time strategy",
    "roguelike",
    "roguelite",
    "rpg",
    "soulslike",
    "strategy",
    "survival",
    "tower defense",
    "turn-based strategy",
    "turn-based tactics",
    "visual novel",
    "word game",
]

_GENRE_ALIASES: dict[str, str] = {
    "action adventure": "adventure",
    "action-roguelike": "action roguelike",
    "action-rpg": "action rpg",
    "arpg": "action rpg",
    "asymmetric": "asymmetric multiplayer",
    "auto-battler": "auto battler",
    "basebuilder": "base building",
    "battle-royale": "battle royale",
    "beat-em-up": "beat em up",
    "br": "battle royale",
    "brawler": "beat em up",
    "brawler game": "beat em up",
    "bullet-heaven": "bullet heaven",
    "bullet heaven survivor": "bullet heaven",
    "bullet hell": "shmup",
    "card battle": "card battler",
    "card-game": "card game",
    "city bulider": "city builder",
    "city-builder": "city builder",
    "citybuilding": "city builder",
    "classic rpg": "crpg",
    "clicker": "idle",
    "clicker game": "idle",
    "co-op": "cooperative",
    "colony management": "colony sim",
    "computer rpg": "crpg",
    "coop": "cooperative",
    "cozy game": "cozy",
    "daily puzzle": "daily challenge",
    "dating simulator": "dating sim",
    "deck bulider": "deckbuilder",
    "deck builder": "deckbuilder",
    "deck-building": "deckbuilder",
    "escape-room": "escape room",
    "extraction-shooter": "extraction shooter",
    "factory builder": "factory automation",
    "farming simulator": "farming sim",
    "fight": "fighting",
    "fighting game": "fighting",
    "first person shooter": "first-person shooter",
    "fps": "first-person shooter",
    "grand-strategy": "grand strategy",
    "hack-and-slash": "hack and slash",
    "hero-shooter": "hero shooter",
    "hidden-object": "hidden object",
    "idle game": "idle",
    "incremental game": "incremental",
    "interactive-fiction": "interactive fiction",
    "japanese rpg": "jrpg",
    "life simulation": "life sim",
    "looter-shooter": "looter shooter",
    "match 3": "match-3",
    "match3": "match-3",
    "metroid-vania": "metroidvania",
    "metroidvaina": "metroidvania",
    "monster tamer": "monster taming",
    "multiplayer online battle arena": "moba",
    "musuo": "musou",
    "mystery game": "mystery",
    "narrative": "narrative adventure",
    "nono": "nonogram",
    "open-world": "open world",
    "p&c": "point and click",
    "picross": "nonogram",
    "point-and-click": "point and click",
    "precision platforming": "precision platformer",
    "psychological": "psychological horror",
    "puzzle-platformer": "puzzle platformer",
    "real time strategy": "real-time strategy",
    "roguelite game": "roguelite",
    "rogue like": "roguelike",
    "rogue lite": "roguelite",
    "rogue-lite": "roguelite",
    "rts": "real-time strategy",
    "run & gun": "run and gun",
    "run-and-gun": "run and gun",
    "sci fi": "sci-fi",
    "shoot em up": "shmup",
    "shoot-em-up": "shmup",
    "social-deduction": "social deduction",
    "soulsborne": "soulslike",
    "souls-like": "soulslike",
    "space simulation": "space sim",
    "srpg": "tactical rpg",
    "strategy rpg": "tactical rpg",
    "tabletop simulator": "tabletop sim",
    "tactical-rpg": "tactical rpg",
    "tcg": "trading card game",
    "text-adventure": "text adventure",
    "third person shooter": "third-person shooter",
    "top down shooter": "top-down shooter",
    "tower defence": "tower defense",
    "tps": "third-person shooter",
    "trading-card-game": "trading card game",
    "turn based combat": "turn-based combat",
    "turn based strategy": "turn-based strategy",
    "turn based tactics": "turn-based tactics",
    "twin stick shooter": "twin-stick shooter",
    "visual-novel": "visual novel",
    "walking sim": "walking simulator",
    "wargames": "wargame",
    "wholesome game": "wholesome",
    "word puzzle": "word game",
}

# ---------------------------------------------------------------------------
# Mechanics
# ---------------------------------------------------------------------------

MECHANICS_TAG_CATALOG: list[str] = [
    "branching narrative",
    "card drafting",
    "co-op",
    "crafting",
    "deck construction",
    "emergent gameplay",
    "fog of war",
    "grid-based",
    "loot systems",
    "meta-progression",
    "one more run",
    "permadeath",
    "physics-based",
    "procedural generation",
    "quick sessions",
    "resource management",
    "run-based",
    "skill trees",
    "speedrun-viable",
    "time pressure",
    "unit management",
    "upgrade systems",
]

FEATURED_MECHANICS_TAGS: list[str] = [
    "co-op",
    "meta-progression",
    "one more run",
    "permadeath",
    "procedural generation",
    "quick sessions",
    "resource management",
    "speedrun-viable",
]

_MECHANICS_ALIASES: dict[str, str] = {
    "branching choices": "branching narrative",
    "card draft": "card drafting",
    "cooperative": "co-op",
    "coop": "co-op",
    "crafting system": "crafting",
    "deck building": "deck construction",
    "emergent": "emergent gameplay",
    "loot": "loot systems",
    "meta progression": "meta-progression",
    "one more turn": "one more run",
    "perma death": "permadeath",
    "perma-death": "permadeath",
    "physics": "physics-based",
    "physics based": "physics-based",
    "proc gen": "procedural generation",
    "procgen": "procedural generation",
    "roguelite progression": "meta-progression",
    "run based": "run-based",
    "runs": "run-based",
    "skill tree": "skill trees",
    "speedrun": "speedrun-viable",
    "speedrunnable": "speedrun-viable",
    "unit control": "unit management",
    "upgrades": "upgrade systems",
}

# ---------------------------------------------------------------------------
# Vibe
# ---------------------------------------------------------------------------

VIBE_TAG_CATALOG: list[str] = [
    "anime aesthetic",
    "atmospheric",
    "brutal difficulty",
    "cartoon",
    "cinematic",
    "dark",
    "dark fantasy",
    "high fantasy",
    "lo-fi",
    "medieval",
    "minimalist",
    "mythology",
    "noir",
    "pixel art",
    "post-apocalyptic",
    "psychological",
    "retro aesthetic",
    "steampunk",
]

FEATURED_VIBE_TAGS: list[str] = [
    "anime aesthetic",
    "atmospheric",
    "dark",
    "dark fantasy",
    "pixel art",
    "post-apocalyptic",
    "psychological",
    "retro aesthetic",
]

_VIBE_ALIASES: dict[str, str] = {
    "anime": "anime aesthetic",
    "anime style": "anime aesthetic",
    "atmospheric game": "atmospheric",
    "brutal": "brutal difficulty",
    "cartoon style": "cartoon",
    "cinematic story": "cinematic",
    "comic": "cartoon",
    "dark fantasy game": "dark fantasy",
    "dark game": "dark",
    "dark tone": "dark",
    "high fantasy game": "high fantasy",
    "lo fi": "lo-fi",
    "lofi": "lo-fi",
    "medival": "medieval",
    "minimal": "minimalist",
    "noir game": "noir",
    "pixel": "pixel art",
    "pixel-art": "pixel art",
    "pixelart": "pixel art",
    "pixels": "pixel art",
    "post apocalyptic": "post-apocalyptic",
    "post-apocalypse": "post-apocalyptic",
    "psychological game": "psychological",
    "retro": "retro aesthetic",
    "retro game": "retro aesthetic",
    "retro style": "retro aesthetic",
    "steam punk": "steampunk",
}

# ---------------------------------------------------------------------------
# Kindred — comparable games whose playerbase overlaps
# ---------------------------------------------------------------------------

KINDRED_TAG_CATALOG: list[str] = [
    "ace attorney",
    "among us",
    "animal crossing",
    "apex legends",
    "baba is you",
    "balatro",
    "baldurs gate",
    "batman arkham",
    "binding of isaac",
    "bioshock",
    "bloodborne",
    "call of duty",
    "castlevania",
    "celeste",
    "cities skylines",
    "civilization",
    "control",
    "counter-strike",
    "crusader kings",
    "cult of the lamb",
    "cuphead",
    "cyberpunk 2077",
    "danganronpa",
    "dark souls",
    "darkest dungeon",
    "dead cells",
    "death stranding",
    "deep rock galactic",
    "destiny 2",
    "diablo",
    "disco elysium",
    "divinity original sin",
    "dont starve",
    "doom",
    "dota",
    "dragon age",
    "dragon quest",
    "dredge",
    "dwarf fortress",
    "dyson sphere program",
    "elden ring",
    "enter the gungeon",
    "factorio",
    "fall guys",
    "fallout",
    "final fantasy",
    "final fantasy xiv",
    "fire emblem",
    "fortnite",
    "ftl",
    "genshin impact",
    "ghost of tsushima",
    "god of war",
    "grand theft auto",
    "hades",
    "half-life",
    "hearthstone",
    "hollow knight",
    "inscryption",
    "into the breach",
    "journey",
    "kenshi",
    "league of legends",
    "lethal company",
    "loop hero",
    "mass effect",
    "mega man",
    "metal gear solid",
    "minecraft",
    "monster hunter",
    "monster train",
    "nier automata",
    "night in the woods",
    "no mans sky",
    "noita",
    "octopath traveler",
    "ori and the blind forest",
    "outer wilds",
    "overwatch",
    "oxygen not included",
    "papers please",
    "path of exile",
    "persona",
    "phasmophobia",
    "planet coaster",
    "pokemon",
    "portal 2",
    "red dead redemption",
    "resident evil",
    "return of the obra dinn",
    "rimworld",
    "risk of rain",
    "rocket league",
    "satisfactory",
    "sekiro",
    "shadow of the colossus",
    "shovel knight",
    "skyrim",
    "slay the spire",
    "sonic",
    "spelunky",
    "spiritfarer",
    "splatoon",
    "starcraft",
    "stardew valley",
    "stray",
    "subnautica",
    "super mario odyssey",
    "terraria",
    "the last of us",
    "the witcher 3",
    "the witness",
    "total war warhammer",
    "tunic",
    "undertale",
    "unpacking",
    "valheim",
    "valorant",
    "vampire survivors",
    "victoria 3",
    "warframe",
    "wordle",
    "world of warcraft",
    "xcom",
    "yakuza",
    "zachtronic games",
    "zelda breath of the wild",
]

FEATURED_KINDRED_TAGS: list[str] = [
    "balatro",
    "baldurs gate",
    "binding of isaac",
    "celeste",
    "dark souls",
    "dead cells",
    "disco elysium",
    "elden ring",
    "factorio",
    "hades",
    "hollow knight",
    "inscryption",
    "minecraft",
    "outer wilds",
    "persona",
    "rimworld",
    "slay the spire",
    "stardew valley",
    "terraria",
    "the witcher 3",
    "undertale",
    "valheim",
    "vampire survivors",
]

_KINDRED_ALIASES: dict[str, str] = {
    "baldurs gate 3": "baldurs gate",
    "bg3": "baldurs gate",
    "botw": "zelda breath of the wild",
    "breath of the wild": "zelda breath of the wild",
    "ck2": "crusader kings",
    "ck3": "crusader kings",
    "cs go": "counter-strike",
    "cs2": "counter-strike",
    "csgo": "counter-strike",
    "d4": "diablo",
    "diablo 2": "diablo",
    "diablo 3": "diablo",
    "diablo 4": "diablo",
    "diablo iv": "diablo",
    "divinity original sin 2": "divinity original sin",
    "dont starve together": "dont starve",
    "don't starve": "dont starve",
    "don't starve together": "dont starve",
    "doom 2016": "doom",
    "doom eternal": "doom",
    "dota 2": "dota",
    "ff14": "final fantasy xiv",
    "ffxiv": "final fantasy xiv",
    "genshin": "genshin impact",
    "grand theft auto 5": "grand theft auto",
    "grand theft auto v": "grand theft auto",
    "gta": "grand theft auto",
    "gta 5": "grand theft auto",
    "gta v": "grand theft auto",
    "hades 2": "hades",
    "hades ii": "hades",
    "lol": "league of legends",
    "minecraft java": "minecraft",
    "monster hunter world": "monster hunter",
    "nier": "nier automata",
    "no man's sky": "no mans sky",
    "overwatch 2": "overwatch",
    "persona 5": "persona",
    "poe": "path of exile",
    "re4": "resident evil",
    "re village": "resident evil",
    "resident evil 4": "resident evil",
    "resident evil village": "resident evil",
    "risk of rain 2": "risk of rain",
    "ror2": "risk of rain",
    "spelunky 2": "spelunky",
    "starcraft 2": "starcraft",
    "starcraft ii": "starcraft",
    "the witcher": "the witcher 3",
    "total war warhammer 3": "total war warhammer",
    "total war warhammer iii": "total war warhammer",
    "witcher": "the witcher 3",
    "witcher 3": "the witcher 3",
    "xcom 2": "xcom",
    "xcom enemy unknown": "xcom",
    "yakuza like a dragon": "yakuza",
    "like a dragon": "yakuza",
}

# ---------------------------------------------------------------------------
# Aggregation — keyed by TagKind for uniform access
# ---------------------------------------------------------------------------

CATALOG_BY_KIND: dict[TagKind, list[str]] = {
    "genre": GENRE_TAG_CATALOG,
    "mechanics": MECHANICS_TAG_CATALOG,
    "vibe": VIBE_TAG_CATALOG,
    "kindred": KINDRED_TAG_CATALOG,
}

FEATURED_BY_KIND: dict[TagKind, list[str]] = {
    "genre": FEATURED_GENRE_TAGS,
    "mechanics": FEATURED_MECHANICS_TAGS,
    "vibe": FEATURED_VIBE_TAGS,
    "kindred": FEATURED_KINDRED_TAGS,
}

ALIASES_BY_KIND: dict[TagKind, dict[str, str]] = {
    "genre": _GENRE_ALIASES,
    "mechanics": _MECHANICS_ALIASES,
    "vibe": _VIBE_ALIASES,
    "kindred": _KINDRED_ALIASES,
}
